# Project information
site_name: SPM Documentation
#site_url: https://www.fil.ion.ucl.ac.uk/spm/#####
site_author: SPM Team
site_description: >-
  Documentation of the SPM Software for neuroimaging

# Repository
repo_url: https://github.com/spm/spm
repo_name: spm/spm
edit_uri: https://github.com/spm/spm-docs/blob/main/docs/

# Copyright
copyright: Copyright &copy; 1991 - 2023 SPM Team and Collaborators

# Configuration
theme:
  name: material
  palette:
   - media: "(prefers-color-scheme)"
     primary: blue grey
     accent: deep orange
     toggle:
       icon: material/brightness-auto
       name: Switch to light mode
   - media: "(prefers-color-scheme: light)"
     scheme: default
     primary: blue grey
     accent: deep orange
     toggle:
       icon: material/brightness-7
       name: Switch to dark mode
   - media: "(prefers-color-scheme: dark)"
     scheme: slate
     primary: blue grey
     accent: deep orange
     toggle:
       icon: material/brightness-4
       name: Switch to system preference
  logo: assets/images/spm_logo_white.png
  favicon: assets/images/spm_favicon.png
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - content.action.edit
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top

nav:
  - 'Home': 'index.md'
  - 'Getting started':
    - 'Installation': 'installation.md'
  - 'Tutorials':
    - 'tutorials/index.md'
    - 'Block Design fMRI':
      - 'Getting started':                 'tutorials/fmri/index.md'
      - 'Preprocessing':
        - 'Introduction':                  'tutorials/fmri/preprocessing/introduction.md'
        - 'Visual inspection of the data': 'tutorials/fmri/preprocessing/visual_inspection.md'
        - 'Removal of dummy scans':        'tutorials/fmri/preprocessing/dummy_scans.md'
        - 'Realignment':                   'tutorials/fmri/preprocessing/realignment.md'
        - 'Slice timing correction':       'tutorials/fmri/preprocessing/slice_timing.md'
        - 'Coregistration':                'tutorials/fmri/preprocessing/coregistration.md'
        - 'Segmentation':                  'tutorials/fmri/preprocessing/segmentation.md'
        - 'Normalisation':                 'tutorials/fmri/preprocessing/normalisation.md'
        - 'Smoothing':                     'tutorials/fmri/preprocessing/smoothing.md'
        - 'Batch interface':               'tutorials/fmri/preprocessing/batch.md'
        - 'Scripting':                     'tutorials/fmri/preprocessing/scripting.md'
      - 'Statistical modelling':
        - 'First-level modelling - block design':         'tutorials/fmri/modelling/block_design.md'
        #- 'First-level modelling - event-related design': 'tutorials/fmri/modelling/event_related_design.md'
        #- 'Group-level modelling':                        'tutorials/fmri/modelling/group_level.md'
    - 'Event-related fMRI':
      - 'Introduction':          'tutorials/faces/index.md'
      - 'Preprocessing':         'tutorials/faces/preprocessing.md'
      - 'Categorical Modelling': 'tutorials/faces/categorical.md'
      - 'Parametric Modelling':  'tutorials/faces/parametric.md'
      - 'Bayesian Analysis':     'tutorials/faces/bayesian.md'
    - 'VBM':
        - 'Getting started':      'tutorials/vbm/VBM-getting-started.md'
        - 'Image processing':     'tutorials/vbm/VBM-image-processing.md'
        - 'Statistical analysis': 'tutorials/vbm/VBM-statistical-analysis.md'
    - 'DCM':
        - 'Overview of DCM':          'tutorials/dcm/index.md'
        - 'DCM for fMRI - 1st level': 'tutorials/dcm/dcm_fmri_first_level.md'
        - 'DCM for fMRI - 2nd level': 'tutorials/dcm/dcm_fmri_second_level.md'
    - 'OPM':
        - 'Evoked response pipeline': 'tutorials/opm_preprocessing/introduction.md'
    - 'Multimodal, multisubject data fusion':
        - 'Overview':                      'tutorials/multi/index.md'  
        - 'Preprocessing':                 'tutorials/multi/preprocessing.md'  
        - 'Evoked analysis':               'tutorials/multi/evoked.md'  
        - 'Time-frequency analysis':       'tutorials/multi/timefrequency.md'  
        - 'fMRI':                          'tutorials/multi/fmri.md'  
        - 'Source':                        'tutorials/multi/source.md'  
        - 'References':                    'tutorials/multi/references.md' 
    - 'M/EEG':
      - 'MEG Source localisation': tutorials/meg_sloc/meg_sloc.md
      - 'EEG Mismatch negativity data': tutorials/mmn/mmn.md
      - 'M/EEG Convolution modelling': tutorials/meeg_firstlevel/meeg_firstlevel.md
    - 'DAiSS':
      - 'Overview of DAiSS':                'tutorials/daiss/index.md'
      - 'Beamforming':             'tutorials/daiss/daiss_beamforming.md'
    - 'Multimodal':
        - 'Introduction': tutorials/multimodal/multimodal.md
        - 'EEG': tutorials/multimodal/eeg.md
        - 'MEG': tutorials/multimodal/meg.md
        - 'fMRI': tutorials/multimodal/fmri.md
        - 'Fusion': tutorials/multimodal/fusion.md
    - 'DCM for Evoked Responses': tutorials/dcm_erp/dcm_erp.md
    - 'DCM for Induced Responses': tutorials/dcm_ir/dcm_ir.md
    - 'DCM for Phase Coupling': tutorials/dcm_phase/dcm_phase.md
    - 'DCM for Steady State Responses': tutorials/dcm_ssr/dcm_ssr.md
    - 'DCM for Cross-Spectral Densities': tutorials/dcm_csd/dcm_csd.md         
  - 'Manual':
    - 'Auditory fMRI data': manual/auditory/auditory.md
    - 'Face group fMRI data': manual/faces_group/face_group.md
    - 'fMRI Model Specification': manual/fmri_spec/fmri_spec.md
    - 'fMRI Model Estimation': manual/fmri_est/fmri_est.md
    - 'Mixed Effects Analysis': manual/mixed_effects/mixed_effects.md
    - 'FieldMap': manual/FieldMap/fieldmap.md
    - 'Dartel': manual/dartelguide/dartelguide.md
    - 'Dynamic Causal Modelling for fMRI': manual/dcm/dcm.md
    - 'PPI': manual/ppi/ppi.md
    - 'Bayesian Model Inference': manual/bms/bms.md
    - 'Dynamic Causal Modelling for resting state fMRI': manual/dcm_rs/dcm_rs.md
    - 'M/EEG':
      - 'Overview': manual/meeg/eeg_overview.md
      - 'Preprocessing': manual/meeg/eeg_preprocessing.md
      - 'Analysis in sensor space ': manual/meeg/eeg_sensoranalysis.md
      - '3D Source Reconstruction': manual/meeg/eeg_imaging.md
      - 'Localization of Equivalent Current Dipoles ': manual/meeg/eeg_VBECD.md
      - 'Dynamic Causal Modelling': manual/meeg/eeg_DCM.md      
    - 'Advanced topics in M/EEG artefact removal': manual/meeg_artefact/meeg_artefact.md
    - 'DCM for fNIRS': manual/dcm_fnirs/dcm_fnirs.md    
    - 'PET': manual/pet/pet.md
    - 'Batch Interface':
      - 'Batch Tutorial': manual/batch/batch.md
      - 'Developer''s Guide': manual/batch/devel.md
  - 'WikiBooks':
    - wikibooks/SPM.md
    - wikibooks/Advice_on_hardware_selection.md
    - wikibooks/Atlases.md
    - wikibooks/Autocorrelation.md
    - wikibooks/Basis_functions.md
    - wikibooks/Batch.md
    - wikibooks/Bayesian_Parameter_Averaging_(BPA).md
    - wikibooks/BIDS.md
    - wikibooks/Block_design.md
    - wikibooks/CI.md
    - wikibooks/Cogent.md
    - wikibooks/Compile_the_gnumex_mex_files.md
    - wikibooks/Concatenation.md
    - wikibooks/Contrasts.md
    - wikibooks/Correlation_and_Regression.md
    - wikibooks/Correlation.md
    - wikibooks/Covariance.md
    - wikibooks/Datasets.md
    - wikibooks/DCM_units.md
    - wikibooks/Design_efficiency.md
    - wikibooks/DICOM.md
    - wikibooks/Docker.md
    - wikibooks/Download.md
    - wikibooks/DTI.md
    - wikibooks/F_and_T_tests.md
    - wikibooks/Faster_SPM.md
    - wikibooks/fonts.md
    - wikibooks/Group_Analysis.md
    - wikibooks/Haemodynamic_Response_Function.md
    - wikibooks/Headless.md
    - wikibooks/How-to.md
    - wikibooks/Importing_data_from_the_scanner.md
    - wikibooks/Inference.md
    - wikibooks/Installation_on_64bit_Linux.md
    - wikibooks/Installation_on_64bit_Mac_OS_(Intel).md
    - wikibooks/Installation_on_64bit_Windows.md
    - wikibooks/Installation_on_Linux.md
    - wikibooks/Installation_on_Mac_OS_(Intel).md
    - wikibooks/Installation_on_Mac_OS_(PowerPC).md
    - wikibooks/Installation_on_SunOS.md
    - wikibooks/Installation_on_Windows.md
    - wikibooks/Julia.md
    - wikibooks/Learning_SPM.md
    - wikibooks/MATLAB.md
    - wikibooks/Non-sphericity.md
    - wikibooks/Normalisation.md
    - wikibooks/Octave.md
    - wikibooks/Parametric_Empirical_Bayes_(PEB).md
    - wikibooks/Percentage_signal_change.md
    - wikibooks/Physio.md
    - wikibooks/Power_Analysis.md
    - wikibooks/PPI.md
    - wikibooks/Programming_intro.md
    - wikibooks/Python.md
    - wikibooks/SEM.md
    - wikibooks/Single_Case_Study.md
    - wikibooks/Slice_Timing.md
    - wikibooks/Spatial_smoothing.md
    - wikibooks/SPM12_MEX_Compilation_on_Windows.md
    - wikibooks/SPM2_MEX_Compilation_on_Windows.md
    - wikibooks/SPM5_MEX_Compilation_on_Windows.md
    - wikibooks/SPM8_MEX_Compilation_on_Windows.md
    - wikibooks/Standalone.md
    - wikibooks/The_DCM_Equation._1._Motivation.md
    - wikibooks/The_DCM_Equation._2._Dynamical_Systems.md
    - wikibooks/The_DCM_Equation._3._Networks_and_Matrices.md
    - wikibooks/The_DCM_Equation._4._The_State_Equation.md
    - wikibooks/Timeseries_extraction.md
    - wikibooks/Two_State_DCM.md
    - wikibooks/VBM.md
    - wikibooks/Working_with_4D_data.md
  - 'Reference': 'reference/index.md'
  - 'Development':
    - 'Introduction': 'development/index.md'
    - 'Git':          'development/git.md'
    - 'Testing':      'development/testing.md'

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  #- mdx_truly_sane_lists
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - smarty
  - toc:
      permalink: true

plugins:
  - mkdocs-video:
      css_style:
        width: "100%"
        height: "42.172vw"
      is_video: True
      video_autoplay: False
  - bibtex:
      bib_file: "docs/assets/bib/spm.bib"
  - search:
      lang: en

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/spm
    - icon: fontawesome/solid/brain
      link: https://www.fil.ion.ucl.ac.uk/spm/

extra_javascript:
  - assets/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
